// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"相關參數設定","status":false,"description":"","parameters":{}},
{"name":"MOG_TitleSplashScreen","status":true,"description":"(v1.0) Adiciona logos antes da tela de título.","parameters":{"Number of Logos":"2","Slash Duration":"60","Splash Fade Duration":"2","Fit Screen Resolution":"true"}}
];
